stvnksslr/uv-migrator

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.4 -> 2024.2.5
<blockquote>
- wip (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.5

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.5 -> 2024.2.6
<blockquote>
- *(actions-rs)* actions-rs is a deprecated org and all their actions are not currently updated, migrating over to maintained versions (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.6

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.6 -> 2024.2.7
<blockquote>
- *(releases)* fully removing deprecated workflows (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.7

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.7 -> 2024.2.8
<blockquote>
- fix(errors in release flow): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.8

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.8 -> 2024.2.9
<blockquote>
- *(workflow fixes + removing goreleaser)* goreleaser is really cool but its a bit of an odd hoop jump for releaser (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.9

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.9 -> 2024.2.10
<blockquote>
- *(releases)* env incorrectly used (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.10

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.10 -> 2024.2.11
<blockquote>
- *(releases)* env incorrectly used (by @stvnksslr)
- chore(removing unused envs): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.2.11

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.2.11 -> 2024.3.0
<blockquote>
- *(pip)* requirements.txt is handled better + cases with no existing pyproject.toml is handled (by @stvnksslr)
- *(readme)* adding pipenv to scope of migration (by @stvnksslr)
- *(migrator)* extracting logic and breaking each implementation into more focused implementations (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.3.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.3.0 -> 2024.3.1
<blockquote>
- *(multiple requirements files)* req.txt files were not properly being sorted into main and dev dependencies and the search code often missed extras (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.3.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.3.1 -> 2024.3.2
<blockquote>
- *(private package indexes)* because of the way the migrator tool is setup it requires adding the packages and creating a lockfile which can cause issues if a given package cannot be seen due to being in a private index this can be fixed by fetching from a global pip.conf or providing a index url (by @stvnksslr)
- *(changing defaults)* By default doesnt pin the python version via a .python-versions file incase the user uses asdf/mise and .tool-versions files (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.3.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.3.2 -> 2024.3.3
<blockquote>
- *(* character)* wildcard or all on dependencies now handled properly when importing (by @stvnksslr)
- *(readme)* fixing some readme language (by @stvnksslr)
- chore(deps bump + readme): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.3.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.3.3 -> 2024.3.4
<blockquote>
- *(poetry)* dependency parsing issues, issues paring ^, >=, <= in dependencies in certain situations (by @stvnksslr)
Fixes #16 
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.3.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.3.4 -> 2024.4.0 (✓ API compatible changes)
<blockquote>
- *(tests)* requirements.txt and poetry parser and migration tests, these should have been in from the getgo but will also work as a better frame of reference for other tools (by @stvnksslr)
- *(readme)* minor readme tune up (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.4.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.5.0 -> 2024.5.1 (✓ API compatible changes)
<blockquote>
- Fix/openssl issues ([#20](https://github.com/stvnksslr/uv-migrator/pull/20)) (by @stvnksslr)
- chore(readme): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.5.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.5.1 -> 2024.5.2 (✓ API compatible changes)
<blockquote>
- *(self-update)* incorrect features to upgrade from releases .tar/.zip (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.5.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.5.3 -> 2024.5.4 (✓ API compatible changes)
<blockquote>
- *(openssl)* one last round of fixes this time for windows (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.5.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.5.4 -> 2024.6.0 (✓ API compatible changes)
<blockquote>
- *(poetry-migrator)* added ability to pull in the description from poetry packages (by @stvnksslr)
- *(linter)* clippy suggestions (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.6.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.7.3 -> 2024.7.4 (✓ API compatible changes)
<blockquote>
- feat(easy install option): (by @stvnksslr)
- chore(readme): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.7.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.8.0 -> 2024.8.1 (✓ API compatible changes)
<blockquote>
- *(tests)* copy paste error with the tests, fixed and the tests correctly get picked up (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.8.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.8.1 -> 2024.8.2 (✓ API compatible changes)
<blockquote>
- *(pyproject)* existing description and version fields were not being carried over correctly, this has been fixed (by @stvnksslr)
- chore(naming fixes): (by @stvnksslr)
- chore(naming for ci workflow): (by @stvnksslr)
- chore(naming for ci workflow): (by @stvnksslr)
- chore(rust format): (by @stvnksslr)
- *(doc strings)* added docstrings for tests (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2024.8.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2024.8.2 -> 2025.0.0 (⚠️ API breaking changes)
```
--- failure function_parameter_count_changed: pub fn parameter count changed ---
Description:
A publicly-visible function now takes a different number of parameters.
ref: https://doc.rust-lang.org/cargo/reference/semver.html#fn-change-arity
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.37.0/src/lints/function_parameter_count_changed.ron
Failed in:
uv_migrator::migrators::run_migration now takes 4 parameters instead of 3, in /tmp/.tmpz2Oqb8/uv-migrator/src/migrators/mod.rs:170
```
<blockquote>
- *(install.sh)* simplified and condensed logic as much as possible so the script is easily auditable (by @stvnksslr)
- *(merge dep groups)* since uv follows …

chore: release v2025.0.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.0.0 -> 2025.1.0 (✓ API compatible changes)
<blockquote>
- *(install.sh)* simplified install script further so that its only concerned with if the chose folder exists, and if its in path. it will not create or modify the users path in anyway (by @stvnksslr)
- *(readme, --help)* reordering options to make more sense for common usage (by @stvnksslr)
- *(readme)* condensing readme (by @stvnksslr)
- chore(fix version): (by @stvnksslr)
- chore(deps + build opts): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.1.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.0 -> 2025.2.1 (✓ API compatible changes)
<blockquote>
- *(release workflow)* goreleaser(rust support) + release plz (by @stvnksslr)
- *(release workflow)* goreleaser(rust support) + release plz (by @stvnksslr)
- *(readme)* formatting (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.1 -> 2025.2.2 (✓ API compatible changes)
<blockquote>
- wip(goreleaser): (by @stvnksslr)
- wip(goreleaser): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.2 -> 2025.2.3 (✓ API compatible changes)
<blockquote>
- wip(goreleaser): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.3 -> 2025.2.4 (✓ API compatible changes)
<blockquote>
- chore(rolling back): (by @stvnksslr)
- *(fixing release names)* lining up release names with rust defaults vs goreleaser defaults (by @stvnksslr)
- *(updating install.sh)* filename formats changed slightly with the move back to goreleaser (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.4 -> 2025.2.5 (✓ API compatible changes)
<blockquote>
- chore(more goreleaser troubleshooting): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.5

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.5 -> 2025.2.6 (✓ API compatible changes)
<blockquote>
- chore(more goreleaser troubleshooting): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.6

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.2.6 -> 2025.2.7 (✓ API compatible changes)
<blockquote>
- feature - pipenv detection and migration ([#41](https://github.com/stvnksslr/uv-migrator/pull/41)) (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.2.7

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.3.0 -> 2025.3.1 (✓ API compatible changes)
<blockquote>
- *(clippy)* fixed some clippy warnings (by @stvnksslr)
- *(dependencies)* self_update released a needed bump .41 -> 42 (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.3.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.3.1 -> 2025.3.2 (✓ API compatible changes)
<blockquote>
- chore(formatting): (by @stvnksslr)
- bugfix(poetry scripts): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.3.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.3.2 -> 2025.3.3 (✓ API compatible changes)
<blockquote>
- *(poetry)* poetry scripts should finally be fixed properly as tracked in issue #44 (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.3.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.3.3 -> 2025.3.4 (✓ API compatible changes)
<blockquote>
- *(poetry authors)* solves issue #49, support for migrating authors was only for setup.py but now supports poetry properly as well (by @stvnksslr)
- *(poetry indexes)* there was an order of operations bug that was filtering the indexes out before they could be migrated introduced in a recent version, this fixes it and also fixes #50 (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.3.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.3.4 -> 2025.4.0
<blockquote>
- *(#53)* will attempt to init the uv project with any version information we can find in the previous packaging tool, if it doesnt find any will set the default python in the users path as is the default in uv (by @stvnksslr)
- *(#51)* adds new build system migration only supports poetry currently (by @stvnksslr)
- *(refactor)* alot of small bugs were cropping up from complex project setups that had lots of different files we were tracking, to make this easier to manage logic wise eveything has been broken into specific migration logic (by @stvnksslr)
- *(python version detection)* simplified logic to increase the chances of uv finding a python version within the range, ie 3.11 …

chore: release v2025.4.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.4.0 -> 2025.5.0
<blockquote>
- *(#55)* updates the migrator to handle the poetry v2 / general python formatting in the pyproject.toml, there is a bit of duplicated code now that needs to be trimmed down and consolidated (by @stvnksslr)
- *(#51)* another crack at improving the build system migration formats from python, ive chosen not to check for the actual path format yet as that will come in a later update (by @stvnksslr)
- chore(update readme): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.5.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.5.1
<blockquote>
- *(#58 - disable-restore)* disable-restore/rollback flag added for easier time doing either incremental migrations or debugging issues with the process (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.5.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.6.0
<blockquote>
- *(#57)* reduces the number of files created in all variations of flags and workflows (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.6.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.6.0 -> 2025.6.1
<blockquote>
- *(readme)* minor formatting change (by @stvnksslr)
- chore(rust 1.85 + rust 2024 edition): (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.6.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.6.1 -> 2025.6.2
<blockquote>
- *(#63)* add warning to explain why this was done (by @stvnksslr)
- *(#63)* fix edge case with uv creating a base python script that can clash with system python (by @stvnksslr)
- *(clippy --fix issue)* when updating to the rust 2024 edition clippy overzelously removed a logging config (by @stvnksslr)
- *(clippy --fix issue)* when updating to the rust 2024 edition clippy overzelously removed a logging config (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.6.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.6.2 -> 2025.6.3
<blockquote>
- *(#63)* missed a code path for checking the script name (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.6.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.7.0 -> 2025.7.1
<blockquote>
- *(#70)* not parsing git urls or packages correctly (by @stvnksslr)
- *(pipenv)* pipenv was pulling dependencies from the lock file in excess of the top level dependencies in the Pipfile this has been correctd (by @stvnksslr)
- *(goreleaser)* removing deprecated config (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.7.1

---

src/migrators/mod.rs

Otherwise dependencies which are only available on those indexes can't be added

fix: add indexes before installing dependencies

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.7.1 -> 2025.8.0
<blockquote>
- feat([#72](https://github.com/stvnksslr/uv-migrator/pull/72)): adding named indexes functionality (by @stvnksslr)
- *(conda)* adding conda support (by @stvnksslr)
- fix([#76](https://github.com/stvnksslr/uv-migrator/pull/76)): didnt have correct logic for hatch conversion (by @stvnksslr)
- add indexes before installing dependencies ([#73](https://github.com/stvnksslr/uv-migrator/pull/73)) (by @benedikt-bartscher)
- *(readme)* changing install url to support additional tools distributed from the same bucket/domain (by @stvnksslr)
- *(readme)* changing install url to support additional tools distributed from the same bucket/domain (by @stvnksslr)
- chore(cleaning up comments): (by …

chore: release v2025.8.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.8.0 -> 2025.8.1
<blockquote>
- fix(misc conda issues):
- chore(fixing install script source):
</blockquote>
</p></details>
---

chore: release v2025.8.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.8.1 -> 2025.8.2
<blockquote>
- *(poetry)* python version constraints parsing bug
</blockquote>
</p></details>
---

chore: release v2025.8.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.8.2 -> 2025.8.3
<blockquote>
- *(rust version)* updating to 1.89
</blockquote>
</p></details>
---

chore: release v2025.8.3

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* `uv-migrator`: 2025.8.3 -> 2025.9.0
<blockquote>
- *(dependency groups)* updated dependency format to follow that of the more recent uv releases which is that of dependency groups via the pep (by @stvnksslr)
* @stvnksslr
</blockquote>
</p></details>
---

chore: release v2025.9.0
